DROP TABLE IF EXISTS public.dea_local_padron;

CREATE TABLE
    public.dea_local_padron (
        id SERIAL PRIMARY KEY juris character varying(20) NOT NULL,
        sector character varying(10),
        ambito character varying(10),
        departamento character varying(20),
        cod_depar integer,
        localidad character varying(60),
        cod_loca bigint,
        cueanexo bigint,
        nombre character varying(70),
        domicilio character varying(80),
        cod_postal character varying(20),
        telefono character varying(50),
        mail character varying(80),
        mod_comun smallint,
        mod_especial smallint,
        mod_adultos smallint,
        ec_mat smallint,
        ec_jar smallint,
        ec_pri smallint,
        ec_sec smallint,
        ec_sec_inet smallint,
        ec_snu smallint,
        ec_snu_inet smallint,
        ec_snu_cursos smallint,
        esp_tem smallint,
        esp_ini smallint,
        esp_pri smallint,
        esp_sec smallint,
        esp_int smallint,
        ad_pri smallint,
        ad_sec smallint,
        ad_fp smallint,
        ad_fp_inet smallint,
        ad_alf smallint,
        hos_ini smallint,
        hos_pri smallint,
        hos_sec smallint,
        tall_art smallint,
        ser_com_ smallint
    );